# Kind Single Node Configuration Template
# This template creates a single-node cluster with only a control-plane node
# Suitable for development, testing, and learning purposes

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: single-node-cluster

networking:
  apiServerPort: 6443
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/16"
  disableDefaultCNI: false
  kubeProxyMode: "iptables"

nodes:
  - role: control-plane
    image: kindest/node:v1.28.0
    
    # Port mappings for ingress and services
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP
    
    labels:
      node-type: control-plane
      environment: development
      cluster-type: single-node
    
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            system-reserved: "cpu=100m,memory=100Mi"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
        etcd:
          local:
            dataDir: /var/lib/etcd

# Container runtime configuration - 国内镜像源配置
containerdConfigPatches:
- |
  version = 2
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = ""
    
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = [
          "https://docker.1ms.run",
          "https://dockerhub.azk8s.cn",
          "https://docker.anyhub.us.kg",
          "https://dockerhub.jobcher.com",
          "https://dockerhub.icu",
          "https://registry-1.docker.io"
        ]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
        endpoint = [
          "https://k8s-gcr.azk8s.cn",
          "https://registry.aliyuncs.com/k8sxio"
        ]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.k8s.io"]
        endpoint = [
          "https://k8s-gcr.azk8s.cn",
          "https://registry.aliyuncs.com/k8sxio"
        ]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
        endpoint = [
          "https://gcr.azk8s.cn",
          "https://registry.aliyuncs.com"
        ]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
        endpoint = [
          "https://quay.azk8s.cn",
          "https://quay-mirror.qiniu.com"
        ]
        
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."dockerhub.azk8s.cn".tls]
        insecure_skip_verify = false
      [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.mirrors.ustc.edu.cn".tls]
        insecure_skip_verify = false
      [plugins."io.containerd.grpc.v1.cri".registry.configs."hub-mirror.c.163.com".tls]
        insecure_skip_verify = false
      [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.docker-cn.com".tls]
        insecure_skip_verify = false

# Usage:
# kind create cluster --config=kind-single-node.yaml
# kubectl get nodes
